version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync --delete build/ s3://god7-bucket.s3-website-ap-northeast-1.amazonaws.com --acl public-read
      - tar cf /tmp/node_modules.tar node_modules
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - /tmp/node_modules.tar
